#datasets_directory: "/home/oliver/Documents/github/Datasets"
#weights_directory: "/home/oliver/Documents/github/VisualLoc_Weights"
datasets_directory: "/Users/olivergrainge/Documents/github/Datasets"
weights_directory: "/Users/olivergrainge/Documents/github/VisualLoc_Weights"

#####################################################################################################################################################
################################################               RUN CONFIGURATION          #####################################################
#####################################################################################################################################################
  
run: 
  datasets: ["inriaholidays"]
  methods: ["amosnet", "hybridnet"]
  num_workers: 12
  pin_memory: False
  batchsize: 10
  device: None

eval: 
  datasets: ["amosnet", "hybridnet"]
  methods: ["amosnet", "hybridnet"]
  partition: "test"
  device: "cpu"
  metrics: ["recall@1", "recall@5"]
  distance: "l2" # either l2 or cosine



