# Desktop
datasets_directory: "/media/oliver/9e8e8649-c1f2-4524-9025-f2c751d67f57/home/oliver/Documents/datasets/Datasets"
weights_directory: "/media/oliver/9e8e8649-c1f2-4524-9025-f2c751d67f57/home/oliver/Documents/VisualLoc_Weights"
# Laptop
#weights_directory: "/Users/olivergrainge/Documents/github/VisualLoc_Weights"
#datasets_directory: "/Users/olivergrainge/Documents/github/Datasets"
#HPC
#datasets_directory: "/ssdfs/users/oeg1n18/datasets"
#weights_directory: "/ssdfs/users/oeg1n18/VisualLoc_Weight"


#####################################################################################################################################################
################################################               RUN CONFIGURATION          #####################################################
#####################################################################################################################################################
  
run: 
  datasets: ["pitts30k"]
  methods: ["resnet50_cosplace", "resnet50_eigenplaces"]
  num_workers: 0
  pin_memory: False
  batchsize: 1
  device: "cpu"

eval: 
  datasets: ["pitts30k"]
  methods: ["resnet50_cosplace", "resnet50_eigenplaces"]
  partition: "test"
  device: "cpu"
  metrics: ["recall@1", "recall@5"]
  distance: "l2" # either l2 or cosine


train: 
  training_method: "gsv_cities"
  method: "resnet50_mixvpr"
  pretrained: False
  image_resolution: [320, 320]
  batch_size: 120
  device: "cuda"
  



