


eval: 
  datasets: 
    - "gardenspointwalking"
  methods: 
    - "netvlad"
  partition: "test"
  device: "cpu"
  input_size: [480, 640, 3]
  
run: 
  datasets: 
    - "gardenspointwalking"
  methods: 
    - "netvlad"
    - "cosplace"
    - "amosnet"
    - "hybridnet" 
    - "mixvpr"
    - "calc"
  partition: "test"
  num_workers: 0
  pin_memory: True
  device: None

train: 
  method: "netvlad"
  seed: 0
  train_batch_size: 2
  infer_batch_size: 1
  criterion: "triplet" # either triplet, sare_ind, sare_joint 
  margin: 0.1
  epochs_num: 1000
  patience: 3
  lr: 0.00001 # learning rate
  optim: adam", #either adam or sgd 
  cache_refresh_rate: 1000
  queries_per_epoch: 5000
  negs_num_per_query: 10
  neg_samples_num: 1000
  mining: "partial" # either partial full random or msls_weighted
  resume: None #path to load checkpoint from 
  device: "cpu" # either cpu or cuda 
  num_workers: 0 # number of workers for the dataloader
  resize: [480, 640] # image resolution 
  test_method: "hard_resize" # post processing method for prediction refinement
  val_positive_dist_threshold: 25
  train_positives_dist_threshold: 25
  recall_values: [1, 5, 10, 20] # recalls to be computed
  
  brightness: 0
  contrast: 0
  saturation: 0
  hue: 0
  rand_perspective: 0
  horizontal_flip: None 
  random_resized_crop: 0
  random_rotation: 0
  #datasets_folder: "/home/oliver/Documents/github/lightweight_VPR/datasets_vg/datasets" # path to all the datasets
  datasets_folder: "/Users/olivergrainge/Documents/github/lightweight_VPR/datasets_vg/datasets"
  dataset_name: "pitts30k"
  save_dir: "default"



