# Desktop
#datasets_directory: "/media/oliver/9e8e8649-c1f2-4524-9025-f2c751d67f57/home/oliver/Documents/datasets/Datasets"
#weights_directory: "/media/oliver/9e8e8649-c1f2-4524-9025-f2c751d67f57/home/oliver/Documents/VisualLoc_Weights"
# Laptop
weights_directory: "/Users/olivergrainge/Documents/github/VisualLoc_Weights"
datasets_directory: "/Users/olivergrainge/Documents/github/Datasets"
#HPC
#datasets_directory: "/scratch/oeg1n18/datasets"
#weights_directory: "/scratch/oeg1n18/VisualLoc_Weights"


#####################################################################################################################################################
################################################               RUN CONFIGURATION          #####################################################
#####################################################################################################################################################
  
run: 
  datasets: ["Pitts30k"]
  methods: ["MixVPR"]
  num_workers: 0
  pin_memory: False
  batchsize: 64
  device: "mps"

eval: 
  datasets: ["pitts30k"]
  methods: ["MixVPR"]
  partition: "test"
  device: "cpu"
  metrics: ["recall@1", "recall@5"]
  distance: "cosine" # either l2 or cosine


train:
  debug: False
  training_method: "gsv_cities_dense"
  method: "MixVPR"
  image_resolution: [320, 320]
  enable_progress_bar: False
  eval_distance: "cosine"
  finetune: False
  checkpoint: False
  num_workers: 16

  # optimization
  optimizer: "adam"
  max_epochs: 30
  batch_size: 120
  lr: 0.0002
  weight_decay: 0
  momentum: 0.9
  warmup_steps: 1
  milestones: 5 10 15 20 25
  lr_mult: 0.3
  loss_name: "MultiSimilarityLoss"
  miner_name: "MultiSimilarityMiner"
  miner_margin: 0.1

  # Pruning
  pruning_type: "magnitude"
  final_sparsity: 0.75
  aggregation_pruning_rate: 2.0
  initial_sparsity: 0.0
  pruning_schedule: "linear"
  pruning_freq: 1


  # Distillation
  teacher_method: "ResNet18_ConvAP"
  teacher_resolution: [224, 224]
  metric_loss_factor: 1.0
  kd_loss_factor: 50.0
  kd_loss_name: "relaxedms" # either rkdangle, rkddistance, mse or kld

  



