datasets_directory: "/home/oliver/Documents/github/Datasets"
datasets_directory: "/media/oliver/9e8e8649-c1f2-4524-9025-f2c751d67f57/home/oliver/Documents/datasets/Datasets"
weights_directory: "/home/oliver/Documents/github/VisualLoc_Weights"
#datasets_directory: "/Users/olivergrainge/Documents/github/Datasets"
#weights_directory: "/Users/olivergrainge/Documents/github/VisualLoc_Weights"

#####################################################################################################################################################
################################################               RUN CONFIGURATION          #####################################################
#####################################################################################################################################################
  
run: 
  datasets: ["inriaholidays"]
  methods: ["amosnet", "hybridnet"]
  num_workers: 12
  pin_memory: False
  batchsize: 40
  device: "cuda"
  descriptor_size: 1024
  backbone: "resnet50"
  aggregation: "gem"

eval: 
  datasets: ["inriaholidays"]
  methods: ["amosnet", "hybridnet"]
  partition: "test"
  device: "cuda"
  metrics: ["recall@1", "recall@5", "gpu_latency", "cpu_latency", "count_flops", "count_params", "measure_memory"]
  distance: "l2" # either l2 or cosine
  backend: "cuda"
  precision: "fp32"
  reload_calib: False
  backbone: "resnet50"
  aggregation: "gem"


train:
  backbone: "resnet50" 
  aggregation: "netvlad"
  lr: 0.00025
  optimizer: 'adam'
  weight_decay: 0.0
  momentum: 0.9
  warmup_steps: 500
  milestones: [5, 10, 15, 25]
  lr_mult: 0.3
  loss_name: "MultiSimilarityLoss"
  miner_name: "MultiSimilarityMiner"
  miner_margin: 0.1
  descriptor_size: 1024




