# Desktop
#datasets_directory: "/media/oliver/9e8e8649-c1f2-4524-9025-f2c751d67f57/home/oliver/Documents/datasets/Datasets"
#weights_directory: "/media/oliver/9e8e8649-c1f2-4524-9025-f2c751d67f57/home/oliver/Documents/VisualLoc_Weights"
# Laptop
weights_directory: "/Users/olivergrainge/Documents/github/VisualLoc_Weights"
datasets_directory: "/Users/olivergrainge/Documents/github/Datasets"
#HPC
#datasets_directory: "/scratch/oeg1n18/datasets"
#weights_directory: "/scratch/oeg1n18/VisualLoc_Weights"


#####################################################################################################################################################
################################################               RUN CONFIGURATION          #####################################################
#####################################################################################################################################################
  
run: 
  datasets: ["pitts30k"]
  methods: ["MixVPR"]
  num_workers: 0
  pin_memory: False
  batchsize: 1
  device: "cpu"

eval: 
  datasets: ["pitts30k"]
  methods: ["MixVPR"]
  partition: "test"
  device: "cpu"
  metrics: ["recall@1", "recall@5"]
  distance: "l2" # either l2 or cosine


train:
  debug: False
  training_method: "gsv_cities_dense"
  method: "ResNet50_MixVPR"
  image_resolution: [320, 320]
  enable_progress_bar: False
  eval_distance: "cosine"
  finetune: False
  checkpoint: False
  num_workers: 0

  # optimization
  optimizer: "adam"
  max_epochs: 20
  batch_size: 12
  lr: 0.0002
  weight_decay: 0
  momentum: 0.9
  warmup_steps: 600
  milestones: 5 10 15 25
  lr_mult: 0.3
  loss_name: "MultiSimilarityLoss"
  miner_name: "MultiSimilarityMiner"
  miner_margin: 0.1

  # Pruning
  pruning_type: "magnitude"
  final_sparsity: 0.99
  initial_sparsity: 0.0
  pruning_schedule: "cosine"
  pruning_freq: 2

  # Distillation
  teacher_method: "MixVPR"
  teacher_resolution: [320, 320]
  contrastive_factor: 1.0
  rkd_distance_factor: 1.0
  rkd_angle_factor: 0.0
  darkrank_factor: 0.0

  



