datasets_directory: "/home/oliver/Documents/github/Datasets"
weights_directory: "/home/oliver/Documents/github/VisualLoc_Weights"
#datasets_directory: "/Users/olivergrainge/Documents/github/Datasets"
#weights_directory: "/Users/olivergrainge/Documents/github/VisualLoc_Weights"

#####################################################################################################################################################
################################################               RUN CONFIGURATION          #####################################################
#####################################################################################################################################################
  
run: 
  datasets: ["inriaholidays"]
  methods: ["amosnet", "hybridnet"]
  num_workers: 0
  pin_memory: False
  batchsize: 10
  device: "cpu"

eval: 
  datasets: ["inriaholidays"]
  methods: ["amosnet", "hybridnet"]
  partition: "test"
  device: "cpu"
  metrics: ["recall@1", "recall@5"]
  distance: "l2" # either l2 or cosine


train: 
  student_method: "gatingresnet"
  teacher_method: "resnet50convap"
  batch_size: 32
  max_epochs: 100
  device: "cuda"
  reload: True
  distillation_type: "beta_random_resize" # either single_resolution, uniform_random_resize, beta_random_resize
  min_mult: 0.5
  max_mult: 0.9
  patience: 500
  learning_rate: 0.0001
  num_workers: 9
  logger: "wandb"

  size: [480, 640]




