

eval: 
  datasets: 
    - "gardenspointwalking"
  methods: 
    - "netvlad"
  partition: "test"
  device: None


run: 
  datasets: 
    - "gardenspointwalking"
  methods: 
    - "netvlad"
  partition: "test"
  num_workers: 0
  pin_memory: True
  device: None



train: 
  method_architecture: "netvlad"
  training_type: "contrastive" # either contrastive or supervised
  negative_mining: "partial"
  dataset: "msls"
  learning_rate: 0.0001
  early_stopping_patience: 3
  loss_function: "triplet" # either triplet, sare, cross_entropy
  optimizer: "adam" # either adam, sgd 




########## Training Datasets ###########
datasets:
  msls_directory: " "
  sanfrancisco_directory: " "


