


eval: 
  datasets: 
    - "gardenspointwalking"
  methods: 
    - "netvlad"
  partition: "test"
  device: "cpu"
  input_size: [480, 640, 3]
  
run: 
  datasets: 
    - "gardenspointwalking"
  methods: 
    - "netvlad"
    - "cosplace"
    - "amosnet"
    - "hybridnet" 
    - "mixvpr"
    - "calc"
  partition: "test"
  num_workers: 0
  pin_memory: False
  batch_size: 10
  device: None

train: 
  ######################## High Level Training Configuration ########################
  seed: 0 # random seed
  training_type: "contrastive" # training type either contrastive or asymmetric_distillation
  dataset_name: "mapillary_sls" # Dataset to train on

  method: "resnet18_gem" # method to train
  train_batch_size: 7 # training batch size
  infer_batch_size: 20 # inference batch size 
  learning_rate: 0.00001 # learning rate
  device: "cuda" # either cpu or cuda for acceleration
  num_workers: 12 # number of workers for the dataloader
  max_epochs: 10000 # maximum number of allowable epochs
  patience: 2 # patience for early stopping
  datasets_folder: "/home/oliver/Documents/github/lightweight_VPR/datasets_vg/datasets" # path to all the datasets
  #datasets_folder: "/Users/olivergrainge/Documents/github/lightweight_VPR/datasets_vg/datasets"
  recall_values: [1, 3, 5, 10, 20]


  ######################## Contrastive Training Configuration #########################
  cache_refresh_rate: 1000 # number of triplets per epoch
  train_positive_dist_threshold: 10
  val_positive_dist_threshold: 25
  neg_num_per_query: 10 # number of negative images per triplet
  mining: "partial" # either partial or random. Partial mines the hardest negatives, random mines random negatives. 
  loss_distance: "l2" # either cosine or l2
  margin: 0.1 # margin of the triplet loss
  val_check_interval: 1 # how many epochs before performing validation 

  ###################### Asymmetric Training Configuration ############################
  student_method: "resnet18_gem"
  teacher_method: "resnet18_gem"
  distillation_type: "uniform_random_resize" # either uniform_random_resize, **** 
  min_size: 320
  max_size: 420
  reload: True # whether to reload the teacher's supervision features or compute new ones 








