datasets_directory: "/media/oliver/9e8e8649-c1f2-4524-9025-f2c751d67f57/home/oliver/Documents/datasets/Datasets"
#weights_directory: "/home/oliver/Documents/github/VisualLoc_Weights"
datasets_directory: "/Users/olivergrainge/Documents/github/Datasets"
weights_directory: "/Users/olivergrainge/Documents/github/VisualLoc_Weights"

#####################################################################################################################################################
################################################               RUN CONFIGURATION          #####################################################
#####################################################################################################################################################
  
run: 
  datasets: ["pitts30k"]
  methods: ["resnet50_cosplace", "resnet50_eigenplaces"]
  num_workers: 0
  pin_memory: False
  batchsize: 1
  device: "cpu"

eval: 
  datasets: ["pitts30k"]
  methods: ["resnet50_cosplace", "resnet50_eigenplaces"]
  partition: "test"
  device: "cpu"
  metrics: ["recall@1", "recall@5"]
  distance: "l2" # either l2 or cosine


train: 
  training_method: "eigenplaces"
  method: "resnet50_gem"
  pretrained: False
  image_resolution: [320, 320]
  batch_size: 32
  device: "cuda"
  



