

training: 
  method_architecture: "netvlad"
  training_type: "contrastive" # either contrastive or supervised
  dataset: "msls"
  learning_rate: 0.0001
  early_stopping_patience: 3
  loss_function: "triplet" # either triplet, sare, cross_entropy
  optimizer: "adam", # either adam, sgd 


inference: 
  precision: "fp32"
  sparsity: "None"


