from .alexnet import AlexNet
from .amosnet import AmosNet
from .calc import CALC
from .convap import ConvAP
from .cosplace import CosPlace
from .hog import HOG
from .hybridnet import HybridNet
from .mixvpr import MixVPR
from .netvlad import NetVLAD
from .regionvlad import RegionVLAD
from .resnet18_gem import ResNet18GeM
