from .amosnet import AmosNet
from .hybridnet import HybridNet
from .base_method import BaseModelWrapper
from .cct_cls import CCT_CLS
from .cct_netvlad import CCT_NetVLAD
from .cct_seqpool import CCT_SEQPOOL
from .dinov2b14_cls import DINOv2B14_CLS
from .anyloc import AnyLoc
from .dinov2s14_cls import DINOv2S14_CLS
from .resnet18_gem import ResNet18_GeM
from .resnet18_netvlad import ResNet18_NetVLAD
from .convap import ConvAP
from .cosplace import CosPlace
from .eigenplaces import EigenPlaces
from .resnet50_gem import ResNet50_GeM
from .mixvpr import MixVPR
from .sfrs import SFRS
from .vit_cls import ViT_CLS
