from .alexnet import AlexNet
from .cosplace import CosPlace
from .hog import HOG
from .netvlad import NetVLAD
from .calc import CALC
from .mixvpr import MixVPR
from .convap import CONVAP
from .hybridnet import HybridNet
from .amosnet import AmosNet
from .regionvlad import RegionVLAD
from .densevlad import DenseVLAD
